version: '3.8'

services:
  db:
    build: .
    restart: always
    environment:
        POSTGRES_DB: "discord-db"
        POSTGRES_PASSWORD: "mypassword"
        DB_USERNAME: "postgres"
        DB_SUPERUSER: "postgres"
        DB_VERSION: "1.0.0"
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/migrations
      - ./bashScripts:/bashScript
      - ./data:/data
      - ./bashScripts/entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
      - ./bashScripts/start_migrations.sh:/docker-entrypoint-initdb.d/start_migrations.sh