version: '3.8'

services:
  db:
    build: .
    restart: always
    environment:
      POSTGRES_DB: discord-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./migration:/docker-entrypoint-initdb.d
