CREATE TABLE "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "online_status" bool,
  "registration_date" datetime,
  "language" varchar(50),
  "theme" varchar(50)
);

CREATE TABLE "servers" (
  "server_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "server_name" varchar NOT NULL,
  "owner_id" integer NOT NULL,
  "creation_date" timestamp NOT NULL
);

CREATE TABLE "channels" (
  "channel_id" integer PRIMARY KEY,
  "channel_name" varchar NOT NULL,
  "server_id" integer NOT NULL,
  "channel_type" varchar
);

CREATE TABLE "messages" (
  "message_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "message_content" text NOT NULL,
  "user_id" integer NOT NULL,
  "channel_id" integer,
  "timestamp" timestamp
);

CREATE TABLE "roles" (
  "role_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_name" varchar NOT NULL,
  "server_id" integer NOT NULL
);

CREATE TABLE "permissions" (
  "permission_id" integer PRIMARY KEY,
  "role_id" integer NOT NULL,
  "channel_id" integer NOT NULL,
  "can_send_messages" boolean,
  "can_delete_messages" boolean,
  "can_edit_messages" boolean,
  "can_create_roles" boolean,
  "can_ban_users" boolean
);

CREATE TABLE "invitations" (
  "invitation_id" integer PRIMARY KEY,
  "server_id" integer NOT NULL,
  "inviter_id" integer,
  "invited_user_id" integer NOT NULL,
  "invitation_date" timestamp
);

CREATE TABLE "moderation_logs" (
  "log_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "moderator_id" integer NOT NULL,
  "user_id" integer,
  "action" varchar NOT NULL,
  "reason" varchar,
  "timestamp" timestamp
);

CREATE TABLE "user_roles" (
  "user_role_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "role_id" integer NOT NULL,
  "server_id" integer NOT NULL
);

CREATE TABLE "emojis" (
  "emoji_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "emoji_name" varchar NOT NULL,
  "emoji_image" varchar NOT NULL,
  "server_id" integer,
  "creator_id" integer NOT NULL,
  "creation_date" timestamp
);

CREATE TABLE "user_settings" (
  "settings_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "theme_preference" varchar,
  "notification_settings" varchar,
  "privacy_settings" varchar,
  "other_preferences" varchar
);

ALTER TABLE "servers" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("user_id");

ALTER TABLE "channels" ADD FOREIGN KEY ("server_id") REFERENCES "servers" ("server_id");

ALTER TABLE "messages" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "messages" ADD FOREIGN KEY ("channel_id") REFERENCES "channels" ("channel_id");

ALTER TABLE "roles" ADD FOREIGN KEY ("server_id") REFERENCES "servers" ("server_id");

ALTER TABLE "permissions" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("role_id");

ALTER TABLE "permissions" ADD FOREIGN KEY ("channel_id") REFERENCES "channels" ("channel_id");

ALTER TABLE "invitations" ADD FOREIGN KEY ("server_id") REFERENCES "servers" ("server_id");

ALTER TABLE "invitations" ADD FOREIGN KEY ("inviter_id") REFERENCES "users" ("user_id");

ALTER TABLE "invitations" ADD FOREIGN KEY ("invited_user_id") REFERENCES "users" ("user_id");

ALTER TABLE "moderation_logs" ADD FOREIGN KEY ("moderator_id") REFERENCES "users" ("user_id");

ALTER TABLE "moderation_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("role_id");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("server_id") REFERENCES "servers" ("server_id");

ALTER TABLE "emojis" ADD FOREIGN KEY ("server_id") REFERENCES "servers" ("server_id");

ALTER TABLE "emojis" ADD FOREIGN KEY ("creator_id") REFERENCES "users" ("user_id");

ALTER TABLE "user_settings" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");
